# Generated by Django 5.1.5 on 2025-04-12 02:38

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('campus', models.CharField(choices=[('W', 'Warner Robins'), ('C', 'Cochran'), ('D', 'Dublin'), ('E', 'Eastman'), ('M', 'Macon'), ('N/A', 'Non Campus')], max_length=3)),
                ('type', models.CharField(choices=[('A', 'Academic'), ('S', 'Social'), ('C', 'Club'), ('V', 'Volunteer')], max_length=1)),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
